import React from "react";
import {
  BookOpen,
  ShieldAlert,
  HelpCircle,
  Database,
  Cpu,
  GitBranch,
  Lock,
  ExternalLink,
  CheckCircle2
} from "lucide-react";

export const AboutAndGuideView: React.FC = () => {
  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      {/* Prominent Medical Disclaimer Banner */}
      <div className="rounded-xl bg-amber-50 border border-amber-300 p-6 text-amber-900 shadow-xs space-y-2">
        <div className="flex items-center gap-2 font-bold text-base text-amber-950">
          <ShieldAlert className="w-5 h-5 text-amber-700 shrink-0" />
          Mandatory Clinical & Regulatory Disclaimer
        </div>
        <p className="text-xs sm:text-sm leading-relaxed text-amber-900">
          This application provides an experimental machine-learning-based risk prediction for educational, research,
          and decision-support evaluation purposes only. It is strictly <strong>not a diagnostic device</strong> and does not
          constitute medical advice. Any prediction generated by LiverGuard must be evaluated in conjunction with
          comprehensive medical history, physical exams, imaging, and qualified physician judgment.
        </p>
      </div>

      {/* Clinical Lab Reference Guide */}
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-xs space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-slate-100">
          <BookOpen className="w-5 h-5 text-teal-700" />
          <h2 className="text-lg font-bold text-slate-900">
            Clinical Laboratory Parameter Reference Guide
          </h2>
        </div>
        <p className="text-xs text-slate-600">
          Liver function tests (LFT) assess hepatic synthesis, excretory capacity, and hepatocyte membrane integrity.
        </p>

        <div className="overflow-x-auto">
          <table className="min-w-full text-xs divide-y divide-slate-200 text-left">
            <thead className="bg-slate-50 font-semibold text-slate-700">
              <tr>
                <th className="py-2.5 px-3">Marker</th>
                <th className="py-2.5 px-3">Standard Reference</th>
                <th className="py-2.5 px-3">Unit</th>
                <th className="py-2.5 px-3">Clinical Significance</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-800">
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">Total Bilirubin</td>
                <td className="py-2.5 px-3 text-slate-600">0.1 – 1.2</td>
                <td className="py-2.5 px-3 font-mono">mg/dL</td>
                <td className="py-2.5 px-3">
                  Combined direct and indirect bilirubin. Elevated in hepatocellular injury, biliary obstruction, or hemolysis.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">Direct Bilirubin</td>
                <td className="py-2.5 px-3 text-slate-600">0.0 – 0.3</td>
                <td className="py-2.5 px-3 font-mono">mg/dL</td>
                <td className="py-2.5 px-3">
                  Conjugated by hepatocytes. Specific indicator of post-hepatic biliary tree obstruction or intrahepatic cholestasis.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">Alkaline Phosphatase (ALP)</td>
                <td className="py-2.5 px-3 text-slate-600">44 – 147</td>
                <td className="py-2.5 px-3 font-mono">IU/L</td>
                <td className="py-2.5 px-3">
                  Enzyme concentrated in biliary epithelial cells. Marked elevation points toward cholestasis, gallstones, or infiltrative liver disorders.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">ALT / SGPT</td>
                <td className="py-2.5 px-3 text-slate-600">7 – 56</td>
                <td className="py-2.5 px-3 font-mono">IU/L</td>
                <td className="py-2.5 px-3">
                  Alanine aminotransferase. Primarily cytoplasmic in liver cells. Highly sensitive and specific marker of acute or chronic hepatocyte damage.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">AST / SGOT</td>
                <td className="py-2.5 px-3 text-slate-600">10 – 40</td>
                <td className="py-2.5 px-3 font-mono">IU/L</td>
                <td className="py-2.5 px-3">
                  Aspartate aminotransferase. Present in both cytoplasm and mitochondria. AST &gt; ALT (ratio &gt; 2.0) is frequently observed in alcoholic liver disease and advanced cirrhosis.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">Total Proteins</td>
                <td className="py-2.5 px-3 text-slate-600">6.0 – 8.3</td>
                <td className="py-2.5 px-3 font-mono">g/dL</td>
                <td className="py-2.5 px-3">
                  Combined serum albumin and globulin pool. Reflects hepatic synthetic capacity and immune responses.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">Albumin</td>
                <td className="py-2.5 px-3 text-slate-600">3.5 – 5.0</td>
                <td className="py-2.5 px-3 font-mono">g/dL</td>
                <td className="py-2.5 px-3">
                  Synthesized exclusively by functional hepatocytes. Half-life ~20 days; depression indicates chronic synthetic decline or cirrhosis.
                </td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-semibold text-slate-900">A/G Ratio</td>
                <td className="py-2.5 px-3 text-slate-600">1.0 – 2.5</td>
                <td className="py-2.5 px-3 font-mono">ratio</td>
                <td className="py-2.5 px-3">
                  Albumin to globulin ratio. Inversion (&lt; 1.0) signifies decreased albumin production and compensatory hypergammaglobulinemia.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Machine Learning Methodology & Architecture */}
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-xs space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-slate-100">
          <Cpu className="w-5 h-5 text-teal-700" />
          <h2 className="text-lg font-bold text-slate-900">
            Machine Learning Engineering & Methodology
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-slate-700 leading-relaxed">
          <div className="space-y-3">
            <h3 className="font-bold text-slate-900 text-sm flex items-center gap-1.5">
              <Database className="w-4 h-4 text-teal-600" />
              1. Dataset & Data Hygiene
            </h3>
            <p>
              Trained on the <strong>Indian Liver Patient Dataset (ILPD)</strong> from the UCI Machine Learning Repository
              (583 records from Andhra Pradesh, India).
            </p>
            <ul className="list-disc list-inside space-y-1 text-slate-600">
              <li><strong>Zero Data Leakage:</strong> Split into 80% train / 20% test before any preprocessing.</li>
              <li><strong>Scikit-learn Pipeline:</strong> Median imputation and standard scaling fit exclusively on training data.</li>
              <li><strong>Imbalance Handling:</strong> Balanced class weighting without artificial synthetic distortion of test distributions.</li>
            </ul>
          </div>

          <div className="space-y-3">
            <h3 className="font-bold text-slate-900 text-sm flex items-center gap-1.5">
              <GitBranch className="w-4 h-4 text-teal-600" />
              2. Screening Threshold Calibration
            </h3>
            <p>
              Standard ML models default to an arbitrary 0.50 probability cutoff. In clinical screening, a false negative
              (missing disease) carries vastly higher human cost than a false positive (prompting follow-up LFT/ultrasound).
            </p>
            <ul className="list-disc list-inside space-y-1 text-slate-600">
              <li>Threshold calibrated to <strong>0.41</strong> via precision-recall optimization.</li>
              <li>Yields <strong>90.4% screening sensitivity/recall</strong> on untouched holdout records.</li>
            </ul>
          </div>

          <div className="space-y-3 md:col-span-2 pt-2 border-t border-slate-100">
            <h3 className="font-bold text-slate-900 text-sm flex items-center gap-1.5">
              <Lock className="w-4 h-4 text-teal-600" />
              3. TreeSHAP Explainability Mechanics
            </h3>
            <p>
              Unlike black-box approximations (like LIME or perturbation sampling), LiverGuard uses <strong>TreeSHAP</strong> (Lundberg et al.),
              which computes exact, mathematically consistent Shapley values across the decision tree ensemble in polynomial time.
              This guarantees that the sum of feature attributions plus the expected dataset baseline strictly equals the model output probability.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
